# Copyright(C) [2025] Advanced Micro Devices, Inc. All rights reserved.

# LLM model
api_key: ""
model_id: dvue-aoai-001-gpt-4.1
temperature: 1.0

# TritonBench
statis_path: "~/TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
py_folder: "~/TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_v1"
instruction_path: "~/TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
corpus_path: "~/TB-eval/tb_eval/data/TritonBench/data/train_crawl.json"
golden_metrics: "~/TB-eval/tb_eval/data/TritonBench/performance_metrics/perf_G/golden_metrics"
perf_ref_folder: null
perf_G_path: "~/TB-eval/tb_eval/data/TritonBench/performance_metrics/perf_G"
py_interpreter: "python"
result_path: null
mem_file: null
start_iter: 0
start_idx: 0
datalen: null

# agent
output_path: "../outputs/20250728_gaagent_des5_gpt41_instrc_profiling.jsonl"
max_iteration: 20
multi_thread: true
ancestor_num: 5
descendant_num: 2
gpu_id: 5
descendant_debug: 2
target_gpu: "MI200"